[NbConvertApp] Converting notebook CNN-SimpleLayered-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-01-17 15:44:20.304512: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-01-17 15:44:20.304557: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df=[[]]
df=pd.DataFrame(df)
for i in trainclasses:
    path = "./Belgium Datasets/BelgiumTSC_Training/Training/"+i+"/GT-"+i+".csv"
    df1 = pd.read_csv(path,sep=';')
    df1['Filename']="./Belgium Datasets/BelgiumTSC_Training/Training/"+i+'/'+df1["Filename"]
    df=pd.concat([df,df1],ignore_index=True)

df['Rotate']=0
df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNotADirectoryError[0m                        Traceback (most recent call last)
[0;32m<ipython-input-1-1d70554e3887>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mtrainclasses[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mpath[0m [0;34m=[0m [0;34m"./Belgium Datasets/BelgiumTSC_Training/Training/"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m"/GT-"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m".csv"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m     [0mdf1[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0mpath[0m[0;34m,[0m[0msep[0m[0;34m=[0m[0;34m';'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m     [0mdf1[0m[0;34m[[0m[0;34m'Filename'[0m[0;34m][0m[0;34m=[0m[0;34m"./Belgium Datasets/BelgiumTSC_Training/Training/"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m'/'[0m[0;34m+[0m[0mdf1[0m[0;34m[[0m[0;34m"Filename"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0mdf[0m[0;34m=[0m[0mpd[0m[0;34m.[0m[0mconcat[0m[0;34m([0m[0;34m[[0m[0mdf[0m[0;34m,[0m[0mdf1[0m[0;34m][0m[0;34m,[0m[0mignore_index[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)[0m
[1;32m    686[0m     )
[1;32m    687[0m [0;34m[0m[0m
[0;32m--> 688[0;31m     [0;32mreturn[0m [0m_read[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    689[0m [0;34m[0m[0m
[1;32m    690[0m [0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    452[0m [0;34m[0m[0m
[1;32m    453[0m     [0;31m# Create the parser.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 454[0;31m     [0mparser[0m [0;34m=[0m [0mTextFileReader[0m[0;34m([0m[0mfp_or_buf[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    455[0m [0;34m[0m[0m
[1;32m    456[0m     [0;32mif[0m [0mchunksize[0m [0;32mor[0m [0miterator[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, f, engine, **kwds)[0m
[1;32m    946[0m             [0mself[0m[0;34m.[0m[0moptions[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m [0;34m=[0m [0mkwds[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    947[0m [0;34m[0m[0m
[0;32m--> 948[0;31m         [0mself[0m[0;34m.[0m[0m_make_engine[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mengine[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    949[0m [0;34m[0m[0m
[1;32m    950[0m     [0;32mdef[0m [0mclose[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m_make_engine[0;34m(self, engine)[0m
[1;32m   1178[0m     [0;32mdef[0m [0m_make_engine[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mengine[0m[0;34m=[0m[0;34m"c"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1179[0m         [0;32mif[0m [0mengine[0m [0;34m==[0m [0;34m"c"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1180[0;31m             [0mself[0m[0;34m.[0m[0m_engine[0m [0;34m=[0m [0mCParserWrapper[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mf[0m[0;34m,[0m [0;34m**[0m[0mself[0m[0;34m.[0m[0moptions[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1181[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1182[0m             [0;32mif[0m [0mengine[0m [0;34m==[0m [0;34m"python"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, src, **kwds)[0m
[1;32m   2008[0m         [0mkwds[0m[0;34m[[0m[0;34m"usecols"[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0musecols[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2009[0m [0;34m[0m[0m
[0;32m-> 2010[0;31m         [0mself[0m[0;34m.[0m[0m_reader[0m [0;34m=[0m [0mparsers[0m[0;34m.[0m[0mTextReader[0m[0;34m([0m[0msrc[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2011[0m         [0mself[0m[0;34m.[0m[0munnamed_cols[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_reader[0m[0;34m.[0m[0munnamed_cols[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2012[0m [0;34m[0m[0m

[0;32mpandas/_libs/parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader.__cinit__[0;34m()[0m

[0;32mpandas/_libs/parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader._setup_parser_source[0;34m()[0m

[0;31mNotADirectoryError[0m: [Errno 20] Not a directory: './Belgium Datasets/BelgiumTSC_Training/Training/Readme.txt/GT-Readme.txt.csv'
NotADirectoryError: [Errno 20] Not a directory: './Belgium Datasets/BelgiumTSC_Training/Training/Readme.txt/GT-Readme.txt.csv'

[NbConvertApp] Converting notebook CNN-SimpleLayered-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-01-17 15:50:26.753106: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-01-17 15:50:26.753177: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df=[[]]
df=pd.DataFrame(df)
for i in trainclasses:
    path = "./Belgium Datasets/BelgiumTSC_Training/Training/"+i+"/GT-"+i+".csv"
    df1 = pd.read_csv(path,sep=';')
    df1['Filename']="./Belgium Datasets/BelgiumTSC_Training/Training/"+i+'/'+df1["Filename"]
    df=pd.concat([df,df1],ignore_index=True)

df['Rotate']=0
df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNotADirectoryError[0m                        Traceback (most recent call last)
[0;32m<ipython-input-1-1d70554e3887>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mtrainclasses[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mpath[0m [0;34m=[0m [0;34m"./Belgium Datasets/BelgiumTSC_Training/Training/"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m"/GT-"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m".csv"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m     [0mdf1[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0mpath[0m[0;34m,[0m[0msep[0m[0;34m=[0m[0;34m';'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m     [0mdf1[0m[0;34m[[0m[0;34m'Filename'[0m[0;34m][0m[0;34m=[0m[0;34m"./Belgium Datasets/BelgiumTSC_Training/Training/"[0m[0;34m+[0m[0mi[0m[0;34m+[0m[0;34m'/'[0m[0;34m+[0m[0mdf1[0m[0;34m[[0m[0;34m"Filename"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0mdf[0m[0;34m=[0m[0mpd[0m[0;34m.[0m[0mconcat[0m[0;34m([0m[0;34m[[0m[0mdf[0m[0;34m,[0m[0mdf1[0m[0;34m][0m[0;34m,[0m[0mignore_index[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)[0m
[1;32m    686[0m     )
[1;32m    687[0m [0;34m[0m[0m
[0;32m--> 688[0;31m     [0;32mreturn[0m [0m_read[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    689[0m [0;34m[0m[0m
[1;32m    690[0m [0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    452[0m [0;34m[0m[0m
[1;32m    453[0m     [0;31m# Create the parser.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 454[0;31m     [0mparser[0m [0;34m=[0m [0mTextFileReader[0m[0;34m([0m[0mfp_or_buf[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    455[0m [0;34m[0m[0m
[1;32m    456[0m     [0;32mif[0m [0mchunksize[0m [0;32mor[0m [0miterator[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, f, engine, **kwds)[0m
[1;32m    946[0m             [0mself[0m[0;34m.[0m[0moptions[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m [0;34m=[0m [0mkwds[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    947[0m [0;34m[0m[0m
[0;32m--> 948[0;31m         [0mself[0m[0;34m.[0m[0m_make_engine[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mengine[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    949[0m [0;34m[0m[0m
[1;32m    950[0m     [0;32mdef[0m [0mclose[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m_make_engine[0;34m(self, engine)[0m
[1;32m   1178[0m     [0;32mdef[0m [0m_make_engine[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mengine[0m[0;34m=[0m[0;34m"c"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1179[0m         [0;32mif[0m [0mengine[0m [0;34m==[0m [0;34m"c"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1180[0;31m             [0mself[0m[0;34m.[0m[0m_engine[0m [0;34m=[0m [0mCParserWrapper[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mf[0m[0;34m,[0m [0;34m**[0m[0mself[0m[0;34m.[0m[0moptions[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1181[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1182[0m             [0;32mif[0m [0mengine[0m [0;34m==[0m [0;34m"python"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, src, **kwds)[0m
[1;32m   2008[0m         [0mkwds[0m[0;34m[[0m[0;34m"usecols"[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0musecols[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2009[0m [0;34m[0m[0m
[0;32m-> 2010[0;31m         [0mself[0m[0;34m.[0m[0m_reader[0m [0;34m=[0m [0mparsers[0m[0;34m.[0m[0mTextReader[0m[0;34m([0m[0msrc[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2011[0m         [0mself[0m[0;34m.[0m[0munnamed_cols[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_reader[0m[0;34m.[0m[0munnamed_cols[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2012[0m [0;34m[0m[0m

[0;32mpandas/_libs/parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader.__cinit__[0;34m()[0m

[0;32mpandas/_libs/parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader._setup_parser_source[0;34m()[0m

[0;31mNotADirectoryError[0m: [Errno 20] Not a directory: './Belgium Datasets/BelgiumTSC_Training/Training/Readme.txt/GT-Readme.txt.csv'
NotADirectoryError: [Errno 20] Not a directory: './Belgium Datasets/BelgiumTSC_Training/Training/Readme.txt/GT-Readme.txt.csv'

[NbConvertApp] Converting notebook Trail8-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 10:50:22.875747: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:22.875792: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 10:50:29.872875: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 10:50:29.929797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.930392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.930961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.931537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.932104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.932646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.933338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.933888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 10:50:29.934039: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.934156: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.934262: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.934368: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.934719: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 10:50:29.967014: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 10:50:29.967202: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.967348: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 10:50:29.967371: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 10:50:29.967739: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 10:50:29.975165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 10:50:29.975211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 10:50:30.734316: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 10:50:30.735434: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Converting notebook Trail5-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 11:07:38.591262: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:38.591331: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 11:07:45.480613: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 11:07:45.548390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.549081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.549729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.550379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.551023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.551706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.552350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.552978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 11:07:45.553157: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.553301: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.553425: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.553547: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.553966: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 11:07:45.594808: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 11:07:45.595107: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.595288: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 11:07:45.595315: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 11:07:45.595706: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 11:07:45.603724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 11:07:45.603782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 11:07:46.493837: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 11:07:46.515505: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Writing 1047163 bytes to Trail5-Belgium.ipynb
[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:07:56.972042: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:07:56.972088: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
start = time.time()

train_images, train_labels = load_train(df)
shape = train_images[0].shape
print(shape)

train_images = train_images.astype('float32') / 255.

train_labels = to_categorical(train_labels, 43)

print('Loading Time: ', time.time() - start)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-1-93d8a36d8ae3>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mtrain_images[0m [0;34m=[0m [0mtrain_images[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0;34m'float32'[0m[0;34m)[0m [0;34m/[0m [0;36m255.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0mtrain_labels[0m [0;34m=[0m [0mto_categorical[0m[0;34m([0m[0mtrain_labels[0m[0;34m,[0m [0;36m43[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mprint[0m[0;34m([0m[0;34m'Loading Time: '[0m[0;34m,[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m-[0m [0mstart[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py[0m in [0;36mto_categorical[0;34m(y, num_classes, dtype)[0m
[1;32m     73[0m   [0mn[0m [0;34m=[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     74[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnum_classes[0m[0;34m)[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 75[0;31m   [0mcategorical[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m,[0m [0my[0m[0;34m][0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m   [0moutput_shape[0m [0;34m=[0m [0minput_shape[0m [0;34m+[0m [0;34m([0m[0mnum_classes[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0mcategorical[0m[0;34m,[0m [0moutput_shape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: index 55 is out of bounds for axis 1 with size 43
IndexError: index 55 is out of bounds for axis 1 with size 43

[NbConvertApp] Converting notebook MobileNetV3-Pending-100.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:27:22.932763: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:22.932821: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 12:27:28.503212: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 12:27:28.560711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.561354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.561951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.562566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.563397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.564151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.564957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.565775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:28.565976: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.566098: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.566265: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.566438: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.566868: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 12:27:28.601111: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 12:27:28.601317: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.601434: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:28.601454: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 12:27:28.601796: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 12:27:28.611187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 12:27:28.611278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 12:27:30.716169: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 12:27:30.735410: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Converting notebook MobileNetV3-Pending-1000.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:27:38.773437: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:38.773483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 12:27:44.482116: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 12:27:44.545617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.546342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.547005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.547665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.548423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.549260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.549980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.550715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:27:44.550935: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.551137: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.551305: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.551433: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.551885: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 12:27:44.599108: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 12:27:44.599602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.599804: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:27:44.599843: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 12:27:44.600331: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 12:27:44.607630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 12:27:44.607664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 12:27:47.001391: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 12:27:47.019437: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:31:27.165710: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:31:27.165777: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
start = time.time()

train_images, train_labels = load_train(df)
shape = train_images[0].shape
print(shape)

train_images = train_images.astype('float32') / 255.

train_labels = to_categorical(train_labels, 43)

print('Loading Time: ', time.time() - start)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-1-93d8a36d8ae3>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mtrain_images[0m [0;34m=[0m [0mtrain_images[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0;34m'float32'[0m[0;34m)[0m [0;34m/[0m [0;36m255.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0mtrain_labels[0m [0;34m=[0m [0mto_categorical[0m[0;34m([0m[0mtrain_labels[0m[0;34m,[0m [0;36m43[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mprint[0m[0;34m([0m[0;34m'Loading Time: '[0m[0;34m,[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m-[0m [0mstart[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py[0m in [0;36mto_categorical[0;34m(y, num_classes, dtype)[0m
[1;32m     73[0m   [0mn[0m [0;34m=[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     74[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnum_classes[0m[0;34m)[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 75[0;31m   [0mcategorical[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m,[0m [0my[0m[0;34m][0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m   [0moutput_shape[0m [0;34m=[0m [0minput_shape[0m [0;34m+[0m [0;34m([0m[0mnum_classes[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0mcategorical[0m[0;34m,[0m [0moutput_shape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: index 55 is out of bounds for axis 1 with size 43
IndexError: index 55 is out of bounds for axis 1 with size 43

[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:38:57.488227: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:38:57.488302: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
start = time.time()

train_images, train_labels = load_train(df)
shape = train_images[0].shape
print(shape)

train_images = train_images.astype('float32') / 255.

train_labels = to_categorical(train_labels, 43)

print('Loading Time: ', time.time() - start)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-1-93d8a36d8ae3>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mtrain_images[0m [0;34m=[0m [0mtrain_images[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0;34m'float32'[0m[0;34m)[0m [0;34m/[0m [0;36m255.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0mtrain_labels[0m [0;34m=[0m [0mto_categorical[0m[0;34m([0m[0mtrain_labels[0m[0;34m,[0m [0;36m43[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mprint[0m[0;34m([0m[0;34m'Loading Time: '[0m[0;34m,[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m-[0m [0mstart[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py[0m in [0;36mto_categorical[0;34m(y, num_classes, dtype)[0m
[1;32m     73[0m   [0mn[0m [0;34m=[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     74[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnum_classes[0m[0;34m)[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 75[0;31m   [0mcategorical[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m,[0m [0my[0m[0;34m][0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m   [0moutput_shape[0m [0;34m=[0m [0minput_shape[0m [0;34m+[0m [0;34m([0m[0mnum_classes[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0mcategorical[0m[0;34m,[0m [0moutput_shape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: index 55 is out of bounds for axis 1 with size 43
IndexError: index 55 is out of bounds for axis 1 with size 43

[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:42:43.626209: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:42:43.626297: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
start = time.time()

train_images, train_labels = load_train(df)
shape = train_images[0].shape
print(shape)

train_images = train_images.astype('float32') / 255.

train_labels = to_categorical(train_labels, 43)

print('Loading Time: ', time.time() - start)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m<ipython-input-1-93d8a36d8ae3>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mtrain_images[0m [0;34m=[0m [0mtrain_images[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0;34m'float32'[0m[0;34m)[0m [0;34m/[0m [0;36m255.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;34m[0m[0m
[0;32m----> 9[0;31m [0mtrain_labels[0m [0;34m=[0m [0mto_categorical[0m[0;34m([0m[0mtrain_labels[0m[0;34m,[0m [0;36m43[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mprint[0m[0;34m([0m[0;34m'Loading Time: '[0m[0;34m,[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m-[0m [0mstart[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py[0m in [0;36mto_categorical[0;34m(y, num_classes, dtype)[0m
[1;32m     73[0m   [0mn[0m [0;34m=[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     74[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m([0m[0mn[0m[0;34m,[0m [0mnum_classes[0m[0;34m)[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdtype[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 75[0;31m   [0mcategorical[0m[0;34m[[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m,[0m [0my[0m[0;34m][0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     76[0m   [0moutput_shape[0m [0;34m=[0m [0minput_shape[0m [0;34m+[0m [0;34m([0m[0mnum_classes[0m[0;34m,[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     77[0m   [0mcategorical[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0mcategorical[0m[0;34m,[0m [0moutput_shape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mIndexError[0m: index 55 is out of bounds for axis 1 with size 43
IndexError: index 55 is out of bounds for axis 1 with size 43

[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:45:06.526638: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:06.526727: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 12:45:29.139915: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 12:45:29.210220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.211057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.211878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.212682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.213490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.214299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.215095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.215978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:45:29.216208: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.216434: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.216580: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.216735: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.217281: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 12:45:29.260495: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 12:45:29.260766: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.260912: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:45:29.260942: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 12:45:29.261588: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 12:45:29.269866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 12:45:29.269919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 12:45:30.094979: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 12:45:30.096414: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 507, in async_setup_kernel
    yield
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model = models.Sequential()
model.add(VGG19(weights=None, include_top=False, input_shape=(32,32,3)))
model.add(layers.BatchNormalization())
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='sigmoid'))
model.add(layers.Dense(num_of_classes, activation='softmax'))

results(model)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyboardInterrupt[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-8456eb2d628b>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mmodel[0m[0;34m.[0m[0madd[0m[0;34m([0m[0mlayers[0m[0;34m.[0m[0mDense[0m[0;34m([0m[0mnum_of_classes[0m[0;34m,[0m [0mactivation[0m[0;34m=[0m[0;34m'softmax'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0mresults[0m[0;34m([0m[0mmodel[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-1-14dc09a8d37d>[0m in [0;36mresults[0;34m(model)[0m
[1;32m      8[0m     [0mmodel[0m[0;34m.[0m[0mcompile[0m[0;34m([0m[0moptimizer[0m[0;34m=[0m[0madam[0m[0;34m,[0m [0mloss[0m[0;34m=[0m[0;34m'categorical_crossentropy'[0m[0;34m,[0m [0mmetrics[0m[0;34m=[0m[0;34m[[0m[0;34m'accuracy'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m     [0mstart[0m [0;34m=[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0mhistory[0m [0;34m=[0m [0mmodel[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mtrain_images[0m[0;34m,[0m [0mtrain_labels[0m[0;34m,[0m [0mbatch_size[0m[0;34m=[0m[0mbatch[0m[0;34m,[0m [0mepochs[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mvalidation_split[0m[0;34m=[0m[0;36m0.2[0m[0;34m,[0m [0mshuffle[0m [0;34m=[0m [0;32mTrue[0m[0;34m,[0m [0mverbose[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m     [0mtrain_time[0m [0;34m=[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m-[0m [0mstart[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m     [0mmodel[0m[0;34m.[0m[0msummary[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py[0m in [0;36mfit[0;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)[0m
[1;32m   1181[0m                 _r=1):
[1;32m   1182[0m               [0mcallbacks[0m[0;34m.[0m[0mon_train_batch_begin[0m[0;34m([0m[0mstep[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1183[0;31m               [0mtmp_logs[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mtrain_function[0m[0;34m([0m[0miterator[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1184[0m               [0;32mif[0m [0mdata_handler[0m[0;34m.[0m[0mshould_sync[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1185[0m                 [0mcontext[0m[0;34m.[0m[0masync_wait[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py[0m in [0;36m__call__[0;34m(self, *args, **kwds)[0m
[1;32m    887[0m [0;34m[0m[0m
[1;32m    888[0m       [0;32mwith[0m [0mOptionalXlaContext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_jit_compile[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 889[0;31m         [0mresult[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    890[0m [0;34m[0m[0m
[1;32m    891[0m       [0mnew_tracing_count[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexperimental_get_tracing_count[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py[0m in [0;36m_call[0;34m(self, *args, **kwds)[0m
[1;32m    915[0m       [0;31m# In this case we have created variables on the first call, so we run the[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    916[0m       [0;31m# defunned version which is guaranteed to never create variables.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 917[0;31m       [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_stateless_fn[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m  [0;31m# pylint: disable=not-callable[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    918[0m     [0;32melif[0m [0mself[0m[0;34m.[0m[0m_stateful_fn[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    919[0m       [0;31m# Release the lock early so that multiple threads can perform the call[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m   3022[0m        filtered_flat_args) = self._maybe_define_function(args, kwargs)
[1;32m   3023[0m     return graph_function._call_flat(
[0;32m-> 3024[0;31m         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
[0m[1;32m   3025[0m [0;34m[0m[0m
[1;32m   3026[0m   [0;34m@[0m[0mproperty[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py[0m in [0;36m_call_flat[0;34m(self, args, captured_inputs, cancellation_manager)[0m
[1;32m   1959[0m       [0;31m# No tape is watching; skip to running the function.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1960[0m       return self._build_call_outputs(self._inference_function.call(
[0;32m-> 1961[0;31m           ctx, args, cancellation_manager=cancellation_manager))
[0m[1;32m   1962[0m     forward_backward = self._select_forward_and_backward_functions(
[1;32m   1963[0m         [0margs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py[0m in [0;36mcall[0;34m(self, ctx, args, cancellation_manager)[0m
[1;32m    594[0m               [0minputs[0m[0;34m=[0m[0margs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    595[0m               [0mattrs[0m[0;34m=[0m[0mattrs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 596[0;31m               ctx=ctx)
[0m[1;32m    597[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    598[0m           outputs = execute.execute_with_cancellation(

[0;32m~/finalYearProject/venv/lib/python3.6/site-packages/tensorflow/python/eager/execute.py[0m in [0;36mquick_execute[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)[0m
[1;32m     58[0m     [0mctx[0m[0;34m.[0m[0mensure_initialized[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     59[0m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
[0;32m---> 60[0;31m                                         inputs, attrs, num_outputs)
[0m[1;32m     61[0m   [0;32mexcept[0m [0mcore[0m[0;34m.[0m[0m_NotOkStatusException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     62[0m     [0;32mif[0m [0mname[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyboardInterrupt[0m: 
KeyboardInterrupt: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_client/manager.py", line 74, in wrapper
    self._ready.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 375, in _async_cleanup_kernel
    await ensure_async(self.km.shutdown_kernel(now=now))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_client/manager.py", line 77, in wrapper
    self._ready.set_exception(e)
asyncio.base_futures.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 562, in async_execute
    self.set_widgets_metadata()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 510, in async_setup_kernel
    await self._async_cleanup_kernel()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 382, in _async_cleanup_kernel
    await ensure_async(self.km.cleanup_resources())
AttributeError: 'NoneType' object has no attribute 'cleanup_resources'
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
XTest = df_test.drop(Y_col_name, axis=1)
yTest = df_test[Y_col_name]
oversampler = RandomOverSampler(sampling_strategy='auto', random_state=42)

# Fit and apply the oversampler to the data
XTest_resampled, yTest_resampled = oversampler.fit_resample(XTest, yTest)

df_test = pd.DataFrame(XTest_resampled, columns=XTest.columns)
df_test[Y_col_name] = y_resampled
df_test[Y_col_name].astype(str)

viewStatistics(df_test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-5c6236c33057>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0mdf_test[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mXTest_resampled[0m[0;34m,[0m [0mcolumns[0m[0;34m=[0m[0mXTest[0m[0;34m.[0m[0mcolumns[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mdf_test[0m[0;34m[[0m[0mY_col_name[0m[0;34m][0m [0;34m=[0m [0my_resampled[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0mdf_test[0m[0;34m[[0m[0mY_col_name[0m[0;34m][0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mstr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'y_resampled' is not defined
NameError: name 'y_resampled' is not defined

[NbConvertApp] Converting notebook VGG19-Belgium.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:47:11.946062: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:11.946123: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 12:47:34.443750: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 12:47:34.521637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.522717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.523806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.524784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.525808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.526788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.527759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.528677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:47:34.529060: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.529252: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.529441: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.529617: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.530293: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 12:47:34.580366: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 12:47:34.580622: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.580760: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:47:34.580790: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 12:47:34.581432: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 12:47:34.587632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 12:47:34.587670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 12:47:35.346572: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 12:47:35.347707: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Converting notebook MobileNetV3-Pending-100.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-05-07 12:58:43.079265: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:43.079323: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-07 12:58:50.866460: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2024-05-07 12:58:50.926262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.927007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.929314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 2 with properties: 
pciBusID: 0000:0a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.930045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 3 with properties: 
pciBusID: 0000:0b:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.930741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 4 with properties: 
pciBusID: 0000:85:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.931402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 5 with properties: 
pciBusID: 0000:86:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.931978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 6 with properties: 
pciBusID: 0000:89:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.932625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 7 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-05-07 12:58:50.932983: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.933100: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.933201: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.933299: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.933685: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2024-05-07 12:58:50.978897: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2024-05-07 12:58:50.979168: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.979286: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/cv2/../../lib:/raid/home/dgx1442/local/lib/:/usr/local/cuda-12.0/lib64:
2024-05-07 12:58:50.979308: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-07 12:58:50.979800: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-07 12:58:50.989424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-05-07 12:58:50.989492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2024-05-07 12:58:53.858189: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2024-05-07 12:58:53.879460: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2194945000 Hz
[NbConvertApp] Writing 593115 bytes to VGG19-Belgium.ipynb
Traceback (most recent call last):
  File "/raid/home/dgx1442/finalYearProject/venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx1442/finalYearProject/venv/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
XTest = df_test.drop(Y_col_name, axis=1)
yTest = df_test[Y_col_name]
oversampler = RandomOverSampler(sampling_strategy='auto', random_state=42)

# Fit and apply the oversampler to the data
XTest_resampled, yTest_resampled = oversampler.fit_resample(XTest, yTest)

df_test = pd.DataFrame(XTest_resampled, columns=XTest.columns)
df_test[Y_col_name] = y_resampled
df_test[Y_col_name].astype(str)

viewStatistics(df_test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-5c6236c33057>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0mdf_test[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mXTest_resampled[0m[0;34m,[0m [0mcolumns[0m[0;34m=[0m[0mXTest[0m[0;34m.[0m[0mcolumns[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mdf_test[0m[0;34m[[0m[0mY_col_name[0m[0;34m][0m [0;34m=[0m [0my_resampled[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0mdf_test[0m[0;34m[[0m[0mY_col_name[0m[0;34m][0m[0;34m.[0m[0mastype[0m[0;34m([0m[0mstr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'y_resampled' is not defined
NameError: name 'y_resampled' is not defined

